// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KRB4GU8HymaLABa8xt8ro6WPlTII5bg',
    appId: '1:293900063930:web:359867df0e09c63557de83',
    messagingSenderId: '293900063930',
    projectId: 'wedding-list-398c6',
    authDomain: 'wedding-list-398c6.firebaseapp.com',
    storageBucket: 'wedding-list-398c6.appspot.com',
    measurementId: 'G-9G3W8GSDFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRf1ezhtdI_fXkKD0RlK5XZaTTxgKmqo',
    appId: '1:293900063930:android:a5deb46f02dba71257de83',
    messagingSenderId: '293900063930',
    projectId: 'wedding-list-398c6',
    storageBucket: 'wedding-list-398c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcut4gTTtAwHtPj3W8UGI3M8Yn8z2O2Bk',
    appId: '1:293900063930:ios:f94de234d56f6de957de83',
    messagingSenderId: '293900063930',
    projectId: 'wedding-list-398c6',
    storageBucket: 'wedding-list-398c6.appspot.com',
    iosClientId: '293900063930-bqido7ggahnq8pm7v7tql8j0deg0illg.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingList',
  );
}
